apiVersion: v1
kind: Service
metadata:
  name: air-web-svc
  labels:
    name: air-web-svc
    tier: front-end
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
  selector:
    name: air-web-pod
    tier: front-end
