apiVersion: v1
kind: Pod
metadata:
  name: air-sch-pod
  labels:
    name: air-sch-pod
    tier: back-end
spec:
  containers:
    - name: air-sch-pod
      image: kaushikarvind/air
      command: ["airflow"]
      args: ["scheduler"]
      ports:
      - containerPort: 8080
      volumeMounts:
      - mountPath: /home/airflow
        name: data-volume
  volumes:
  - name: data-volume
    hostPath: 
      path: /home/airflow
      type: Directory
